# GitHub's actions.yml
name: Upload posts to S3
on: [push]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'me-south-1'
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: static/posts.json